# Generated by Django 6.1 on 2026-08-22 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('heading', 'Heading'), ('checklist', 'Checklist'), ('progress', 'Progress'), ('number', 'Number'), ('chart', 'Chart'), ('table', 'Table')], max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blok',
                'verbose_name_plural': 'Bloklar',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Yeni Sayfa', max_length=200)),
                ('icon', models.CharField(blank=True, default='📄', max_length=50)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.page')),
            ],
            options={
                'verbose_name': 'Sayfa',
                'verbose_name_plural': 'Sayfalar',
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
