# Generated by Django 6.1 on 2026-08-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('heading', 'Heading'), ('checklist', 'Checklist'), ('progress', 'Progress'), ('number', 'Number'), ('chart', 'Chart'), ('table', 'Table'), ('image', 'Image')], max_length=20),
        ),
    ]
