# Generated by Django 6.1 on 2026-08-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_block_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('heading', 'Heading'), ('checklist', 'Checklist'), ('progress', 'Progress'), ('number', 'Number'), ('chart', 'Chart'), ('table', 'Table'), ('image', 'Image'), ('bulleted_list', 'Bulleted List'), ('numbered_list', 'Numbered List'), ('divider', 'Divider')], max_length=20),
        ),
    ]
